### ISSUE TITLE
TypeError: HelloSignSDK.SignatureRequestApi is not a constructor

### ISSUE THREAD

**Issue by ronaldl29** [HelloFax/hellosign-nodejs-sdk#110]
```
import * as HelloSignSDK from "hellosign-sdk";

const api = new HelloSignSDK.SignatureRequestApi();

// Configure HTTP basic authorization: api_key
api.username = "YOUR_API_KEY";

// or, configure Bearer (JWT) authorization: oauth2
// $config->setAccessToken("YOUR_ACCESS_TOKEN");

const signatureRequestId = "fa5c8a0b0f492d768749333ad6fcc214c111e967";

const result = api.signatureRequestFiles(signatureRequestId);
result.then(response => {
  console.log(response.body);
}).catch(error => {
  console.log("Exception when calling HelloSign API:");
  console.log(error.body);
});
```

I am copying the code from the Hellosign docs exactly. Node v18.8.0. 

And getting this error:
```
TypeError: HelloSignSDK.SignatureRequestApi is not a constructor
    at file:///home/ronald/Projects/hellosign-microservice/test.js:3:13
    at ModuleJob.run (internal/modules/esm/module_job.js:183:25)
    at async Loader.import (internal/modules/esm/loader.js:178:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)
    at async handleMainPromise (internal/modules/run_main.js:59:12)
```

**Comment by JS1209** [comment]
Same problem here, none of the examples work

**Comment by ronaldl29** [comment]
I ended up having to move to a different e-signature company unfortunately. @JS1209

**Comment by JS1209** [comment]
Nice, thanks guys, I will check that out

**Comment by jtreminio-dropbox** [comment]
Howdy!

I just tested this locally in an empty directory:

package.json: 

```json
{
  "name": "npm-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "type": "module",
  "dependencies": {
    "hellosign-sdk": "^6.0.0-beta"
  }
}
```

test.js:

```javascript
import * as HelloSignSDK from "hellosign-sdk";

const api = new HelloSignSDK.SignatureRequestApi();

// Configure HTTP basic authorization: api_key
api.username = "YOUR_API_KEY";

// or, configure Bearer (JWT) authorization: oauth2
// $config->setAccessToken("YOUR_ACCESS_TOKEN");

const signatureRequestId = "fa5c8a0b0f492d768749333ad6fcc214c111e967";

const result = api.signatureRequestFiles(signatureRequestId);
result.then(response => {
  console.log(response.body);
}).catch(error => {
  console.log("Exception when calling HelloSign API:");
  console.log(error.body);
});
```

```
$ node -v
v16.13.2

$ node test.js
Exception when calling HelloSign API:
_ErrorResponse {
  error: _ErrorResponseError {
    errorMsg: 'Unauthorized api key',
    errorName: 'unauthorized',
    errorPath: undefined
  }
}
```

Note that this version of the SDK is still marked as Beta and not yet suitable for production usage (although it is very close!).

**Comment by erosiec** [comment]
Hi @ronaldlong46, @JS1209 

The samples in the docs are for the new beta SDK. The errors you're running into could be due to using the legacy Node SDK, but referencing the beta. 

Use this to get the beta: 

`npm install hellosign-sdk@6.0.0-beta`

Hope this helps!

**Comment by TaylorKrusen** [comment]
Hi! 

Sorry about the samples and differences in SDK versions. I manage the docs and should have made it more clear that the samples are using the beta SDKs. Thanks for posting the issue, though! I'm working on a PR for the docs right now to address that. Additionally, our new SDKs should be out of beta soon! 

Closing this issue but please re open as needed.

**Comment by ronaldl29** [comment]
Hi @TaylorKrusen Thanks for the reply! Are the new SDKs out of beta?
