### ISSUE TITLE
"Client IDs" should be accepted as snake case or camel case

### ISSUE THREAD

**Issue by freddyrangel** [HelloFax/hellosign-nodejs-sdk#3]
I'm working on a Node demo, going off this example: [Embedded Signing Example](https://www.hellosign.com/api/embeddedSigningExample).  Some options are snake case (like test_mode) while others, specifically Client ID, must strictly be camelcase. `client_id` will return:

```
{ [Error: No client id provided]
  type: 'bad_request',
  message: 'No client id provided',
  stack: 'Error: No client id provided
at Error._Error (/Users/freddyrangel/repositories/sandbox/embedded_signing_node/node_modules/hellosign-sdk/lib/Error.js:36:19)
at Function.HelloSignError.generate (/Users/freddyrangel/repositories/sandbox/embedded_signing_node/node_modules/hellosign-sdk/lib/Error.js:79:12)
at IncomingMessage.<anonymous> (/Users/freddyrangel/repositories/sandbox/embedded_signing_node/node_modules/hellosign-sdk/lib/HelloSignResource.js:172:56)\
at emitNone (events.js:72:20)
at IncomingMessage.emit (events.js:166:7)
at endReadableNT (_stream_readable.js:893:12)
at doNTCallback2 (node.js:429:9)
at process._tickCallback (node.js:343:17)' }
```

**Comment by renderf0x** [comment]
Thanks @freddyrangel.

Solved here:
https://github.com/HelloFax/hellosign-nodejs-sdk/commit/aaa74b2dac80a970de8de7e4a1ff8d2f3f71b137

This should be updated for v1.1.4 of the SDK.

`client_id` is correct for this, but keeping `clientId` support for compatibility.
If both are present, the former will take precedence.
