### ISSUE TITLE
Error: This request cannot be signed yet

### ISSUE THREAD

**Issue by mebibou** [HelloFax/hellosign-nodejs-sdk#52]
We are experiencing this error in our application:

```
{ Error: This request cannot be signed yet 
  message: 'This request cannot be signed yet', 
  stack: 'Error: This request cannot be signed yet
    at _Error (/app/node_modules/hellosign-sdk/lib/Error.js:36:19)
    at Function.HelloSignError.generate (/app/node_modules/hellosign-sdk/lib/Error.js:79:12)
    at IncomingMessage.<anonymous> (/app/node_modules/hellosign-sdk/lib/HelloSignResource.js:173:56)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)' } 
```

Not sure exactly which function call triggers this as the stack doesn't include the exact origin

**Comment by alexmac05** [comment]
We are working on this issue in a reference number 406368 in a zen desk ticket.

**Comment by nathanbuchar** [comment]
Thanks @alexmac05 !

**Comment by mebibou** [comment]
@alexmac05 any news on this? we are still seing this issue frequently

**Comment by latoyazamill** [comment]
Closing the loop here - the initial ticket was responded to in August 2019. If you are still experiencing this issue, please contact apisupport@hellosign.com.
