### ISSUE TITLE
Is this library interfering with nock in some way?

### ISSUE THREAD

**Issue by JaredCE** [HelloFax/hellosign-nodejs-sdk#79]
I'm trying to use [nock](https://github.com/nock/nock) to intercept requests to your services and mock out a response, however i seem to be receiving this from your library when i do:

```
Error: write after end
    at Constructor._Error (/Users/jared/Projects/scratch/js-server/node_modules/hellosign-sdk/lib/Error.js:36:19)
    at new Constructor (/Users/jared/Projects/scratch/js-server/node_modules/hellosign-sdk/lib/utils.js:112:19)
    at OverriddenClientRequest.<anonymous> (/Users/jared/Projects/scratch/js-server/node_modules/hellosign-sdk/lib/HelloSignResource.js:214:17)
    at OverriddenClientRequest.emit (events.js:210:5)
    at /Users/jared/Projects/scratch/js-server/node_modules/nock/lib/intercepted_request_router.js:145:34
    at processTicksAndRejections (internal/process/task_queues.js:75:11) {
  type: 'HelloSignError',
  stack: 'Error: write after end\n' +
    '    at Constructor._Error (/Users/jared/Projects/scratch/js-server/node_modules/hellosign-sdk/lib/Error.js:36:19)\n' +
    '    at new Constructor (/Users/jared/Projects/scratch/js-server/node_modules/hellosign-sdk/lib/utils.js:112:19)\n' +
    '    at OverriddenClientRequest.<anonymous> (/Users/jared/Projects/scratch/js-server/node_modules/hellosign-sdk/lib/HelloSignResource.js:214:17)\n' +
    '    at OverriddenClientRequest.emit (events.js:210:5)\n' +
    '    at /Users/jared/Projects/scratch/js-server/node_modules/nock/lib/intercepted_request_router.js:145:34\n' +
    '    at processTicksAndRejections (internal/process/task_queues.js:75:11)',
  rawType: undefined,
  code: 'ERR_STREAM_WRITE_AFTER_END',
  param: undefined,
  message: 'write after end',
  detail: undefined,
  raw: Error: write after end
      at InterceptedRequestRouter.handleWrite (/Users/jared/Projects/scratch/js-server/node_modules/nock/lib/intercepted_request_router.js:143:19)
      at OverriddenClientRequest.req.write (/Users/jared/Projects/scratch/js-server/node_modules/nock/lib/intercepted_request_router.js:90:35)
      at InterceptedRequestRouter.handleEnd (/Users/jared/Projects/scratch/js-server/node_modules/nock/lib/intercepted_request_router.js:198:9)
      at OverriddenClientRequest.req.end (/Users/jared/Projects/scratch/js-server/node_modules/nock/lib/intercepted_request_router.js:91:33)
      at OverriddenClientRequest.<anonymous> (/Users/jared/Projects/scratch/js-server/node_modules/hellosign-sdk/lib/HelloSignResource.js:423:21)
      at OverriddenClientRequest.emit (events.js:210:5)
      at InterceptedRequestRouter.startPlayback (/Users/jared/Projects/scratch/js-server/node_modules/nock/lib/intercepted_request_router.js:302:11)
      at InterceptedRequestRouter.maybeStartPlayback (/Users/jared/Projects/scratch/js-server/node_modules/nock/lib/intercepted_request_router.js:253:12)
      at InterceptedRequestRouter.handleEnd (/Users/jared/Projects/scratch/js-server/node_modules/nock/lib/intercepted_request_router.js:200:10)
      at OverriddenClientRequest.req.end (/Users/jared/Projects/scratch/js-server/node_modules/nock/lib/intercepted_request_router.js:91:33)
      at Socket.<anonymous> (/Users/jared/Projects/scratch/js-server/node_modules/hellosign-sdk/lib/HelloSignResource.js:417:29)
      at Socket.emit (events.js:210:5)
      at InterceptedRequestRouter.connectSocket (/Users/jared/Projects/scratch/js-server/node_modules/nock/lib/intercepted_request_router.js:128:14)
      at /Users/jared/Projects/scratch/js-server/node_modules/nock/lib/intercepted_request_router.js:69:33
      at processTicksAndRejections (internal/process/task_queues.js:75:11) {
    code: 'ERR_STREAM_WRITE_AFTER_END'
  }
}
```

This is based on the code:

```
const helloAPI = require('hellosign-sdk')({key: process.env.API_KEY});
class CreateLive {
  constructor() {

  }

  async acknowledge(header, body) {
    const contractFile = await this._download(body)
      .catch((err) => {
        throw err;
      });
  }

  async _download(body) {
    const requestID = body.signature_request.signature_request_id;
    const downloadedData = await helloAPI.signatureRequest.download(requestID, {file_type: 'pdf'})
      .then((res) => {
        return new Promise((resolve, reject) => {
          let downloadData = Buffer.from('');
          res.on('data', (data) => {
            downloadData = Buffer.concat([downloadData, data]);
          });
          res.on('end', () => {
            resolve(downloadData);
          });
        });
      })
      .catch((err) => {
        console.log(err);
        throw err;
      });
    console.log(downloadedData)
    return downloadedData;
  }
}
module.exports = CreateLive;
```

then using nock in my tests here:

```
// common.js
'use strict';

global.chai = require('chai');
global.chai.should();

global.expect = global.chai.expect;
global.sinon = require('sinon');

global.sinonChai = require('sinon-chai');
global.chai.use(global.sinonChai);

global.nock = require('nock');
```

```
// .mocharc.js
'use strict';

module.exports = {
  require: '/Users/jared/Projects/scratch/js-server/test/common.js',
  harmony: true,
  recursive: true,
  bail: true
};
```

```
const CreateLive = require('../src/Events/Event/CreateLive');
describe('CreateLive', () => {
  describe('acknowledge', function() {
    it('should call _download', async () => {
      const event = getEvent() // code to get a mocked out hellosign event
      const contract = getContract() // code to get a contract (.pdf file)
      nock('https://api.hellosign.com:443', {"encodedQueryParams":true})
          .get('/v3/signature_request/files/' + event.body.signature_request.signature_request_id, "file_type=pdf")
          .query({"file_type":"pdf"})
          .reply(200, contract, [
            'Access-Control-Allow-Headers',
            'Authorization, Origin, X-Requested-With, Content-Type, Accept',
            'Access-Control-Allow-Methods',
            'GET, POST, OPTIONS',
            'Access-Control-Allow-Origin',
            '*',
            'Cache-Control',
            'cache-control=must-revalidate',
            'Content-Description',
            'File Transfer',
            'Content-Disposition',
            'attachment; filename="abcd"',
            'Content-Transfer-Encoding',
            'binary',
            'Content-Type',
            'application/pdf',
            'Date',
            'Fri, 26 Jun 2020 16:39:49 GMT',
            'ETag',
            '"57c83-0"',
            'Expires',
            'Sat, 26 Jul 1997 05:00:00 GMT',
            'Last-Modified',
            'Fri, 26 Jun 2020 16:39:50 GMT',
            'P3P',
            'CP="NOP3PPOLICY"',
            'Pragma',
            'public: 1',
            'Server',
            'Apache',
            'Strict-Transport-Security',
            'max-age=15768000',
            'Content-Length',
            '359555',
            'Connection',
            'Close'
          ]);
        const createEvent = new CreateLive();
        const actual = await createEvent.acknowledge(event.headers, event.body)
          .catch(function(err) {
            console.log(err);
            expect(function() { throw err })
              .to.not.throw();
          });
    });
  });
});
```

Dependencies:
```
"chai": "^4.2.0",
    "mocha": "^8.1.1",
    "nock": "^13.0.4",
    "sinon": "^9.0.3",
    "sinon-chai": "^3.5.0"
"hellosign-sdk": "^1.6.0",
```

**Comment by hazemhamedhs** [comment]
Hi Jared,

This is Hazem from API support.

Would you mind getting back to us by creating a ticket to apisupport@hellosign.com with what the HelloSign SDK is doing in response when hitting the Get Files endpoint outside of the Nock implementation? 

I will be on the look-out for your ticket in our queue.

**Comment by toymachiner62** [comment]
@JaredCE did you ever get this resolved? Having similar issues.

**Comment by toymachiner62** [comment]
The issue seems to be with nock v13. I have some tests that work just fine using nock v12, but when I upgrade to nock v13 i'm getting these same errors.

Please reopen.

**Comment by latoyazamill** [comment]
Hi @toymachiner62,

This is LaToya from API support.

Would you mind getting back to us by creating a ticket to apisupport@hellosign.com with what the HelloSign SDK is doing in response when hitting the endpoint in your test suite outside of the Nock implementation?

We will be on the look-out for your ticket in our queue.

**Comment by JaredCE** [comment]
@toymachiner62 

When i asked about this, i got this response:

> Digging deeper into the Node SDK, the error does seem to be due to the way we're making the request in our SDK (looks originate from this line, we call req.end( two times which is what triggers the Nock error). Yet, we are not able figure out if what we're doing is actually an error or not.

As you say, it started happening with Node 13... I've suppressed the tests for now.  Hopefully this might get fixed in the future when they move off of the request package?

**Comment by toymachiner62** [comment]
@JaredCE I was able to get it figured out by creating an issue on the nock repo. Seems it was a bug in nock. Solution is here https://github.com/HelloFax/hellosign-nodejs-sdk/issues/80#issuecomment-725212634
